service: serverless-task-board
custom:
  s3Sync:
    - bucketName: task-board-app
      localDir: dist

plugins:
  - serverless-s3-sync
provider:
  name: aws
  runtime: nodejs14.x

resources:
  Resources:
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: task-board-app
        WebsiteConfiguration:
          IndexDocument: index.html
